name: Java-Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    name: my-spc
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Build Java with Maven 
        run: mvn package
      - name: Build and analyze 
        uses: sonarsource/sonarqube-scan-action@v5  
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.organization=srinivaskadudhuram
            "-Dsonar.projectName=petclinic"  
            -Dsonar.projectkey=srinivaskadudhuram